name: Stephen Butkus
favicon: null
layout_spectrum: 0.75837
typography_spectrum: 0.49681
title: Photographer Stephen Butkus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.12421550322324038
  saturation: 0.25
  rhythmicContrast: 0.6417846165131778
purpose: []
